---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  build_ppc:
    runs-on: ubuntu-latest
    container:
      image: amigadev/crosstools:ppc-amigaos
    name: build_os4
    steps:
      - uses: actions/checkout@v3
      - name: build_os4
        id: build_os4
        run: |
          make -f Makefile zmakebas
          mv ./zmakebas ./zmakebas_amigaos4
      - name: Upload Amiga PPC build
        uses: actions/upload-artifact@v4
        with:
          name: zmakebas_os4
          path: ./zmakebas_amigaos4
  build_68k:
    runs-on: ubuntu-latest
    container:
      image: walkero/docker4amigavbcc:latest-m68k
    name: build_os3
    steps:
      - uses: actions/checkout@v3
      - name: buildos3
        id: buildos3
        run: |
          make -f Makefile.68k zmakebas
          mv ./zmakebas ./zmakebas_amigaos3
      - name: Upload Amiga 68k build
        uses: actions/upload-artifact@v4
        with:
          name: zmakebas_os3
          path: ./zmakebas_amigaos3
  tagged-release:
    name: "Tagged Release"
    needs: [build_ppc, build_68k]
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
        with:
          repository: chris-y/rman
      - name: build_rman
        id: build_rman
        run: make -f Makefile
      - uses: actions/upload-artifact@v4
        with:
          name: rman
          path: ./rman
      - uses: actions/checkout@v3
      - name: Download rman
        uses: actions/download-artifact@v4
        with:
          name: rman
          path: rman
      - name: build_guide
        id: build_guide
        run: |
          chmod a+x ./rman/rman
          make -f Makefile
      - uses: actions/download-artifact@v4
        with:
          name: zmakebas_os3
      - uses: actions/download-artifact@v4
        with:
          name: zmakebas_os4
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./zmakebas.guide
            ./zmakebas_amigaos3
            ./zmakebas_amigaos4
