---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          repository: chris-y/rman
      - name: build_rman
        id: build_rman
        run: make -f Makefile
      - uses: actions/upload-artifact@v1
        with:
          name: rman
          path: ./rman
      - uses: actions/checkout@v2
      - name: Download rman
        uses: actions/download-artifact@v1
        with:
          name: rman
      - name: build_guide
        id: build_guide
        run: |
          chmod a+x ./rman/rman
          make -f Makefile
      - uses: actions/upload-artifact@v1
        with:
          name: zmakebas.guide
          path: ./zmakebas.guide
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./zmakebas.guide
